### ISSUE TITLE
As a developer, I should understand socket.io to connect users to other users

### ISSUE THREAD

**Issue by rebeccahom** [nyu-software-engineering/drawing-with-friends#13]
Acceptance criteria:
- [x] I understand how to connect two clients to each other 
- [x] I understand how to emit an event to the socket
- [x] I understand how to listen to events

Estimation of Work:
M

Notes:
Refer to the docs [here](https://socket.io/docs/) to learn more

**Comment by jeph** [comment]
Socket io allows users to create namespaces. Right now I'm thinking that we should be able to use namespaces to represent individual lobbies of the game. Namespaces can be joined by the client natively. Then we can have the drawing client emit socket.io draw events with location relative to canvas (0,0) point and stream those to the server which then broadcasts it to everything in the room. Note that this implementation would not allow disconnected clients to rejoin a lobby and see canvas state that accurately reflects what is needed.

Some things to note about P5.js: it makes modifications directly to the DOM, so my fear is that it will not be compatible which React. I found some npm libraries that wrap p5.js for react as well as some other react specific canvas components (that are unfortunately less powerful) so we might want to do extra research to make sure that our canvas doesn't cause bugs with react.

**Comment by rebeccahom** [comment]
I've gotten p5 to work with React in the past so it's definitely compatible. However I didn't use an interactive sketch so I'm not sure how that will turn out, but I'll test it later and see how it goes.
