### ISSUE TITLE
As a user, I want to create a room, so that I can invite my friends

### ISSUE THREAD

**Issue by EricSihaoLin** [nyu-software-engineering/drawing-with-friends#2]
## Description:
After the skeleton of the website is built, the user must be able to perform functional actions. The first action should be creating a room to that they can invite other users to join the same room to play.

## Acceptance Criteria:
- [x] User can navigate to the website
- [x] User can create a room
- [x] User can get a generated code to share with friends to invite them to the room
- [x] User can send the code to their friends

## Work estimate: 
M

**Comment by bloombar** [comment]
@nyu-software-engineering/spring-2019-drawing-with-friends - nice job writing the user story details on all these.

**Comment by bloombar** [comment]
But please break out each task into its own issue with the "task" label, and place them into the Tasks column.
