### ISSUE TITLE
As a user, I should be able to indicate when I am ready to play, so the game can start

### ISSUE THREAD

**Issue by EricSihaoLin** [nyu-software-engineering/drawing-with-friends#5]
## Description:
Once the room has at least two people, they can indicate themselves as ready, so that the game can start once everyone is ready.

## Acceptance Criteria:
- [ ] Users can toggle their "ready" status (#41 )
- [ ] The user who created the session can start the game successfully (#42)

## Work estimate: 
S

**Comment by rebeccahom** [comment]
This feature is complex and will introduce many bugs to our product and therefore we will not implement it in the given time that we have.
