### ISSUE TITLE
Display the current round

### ISSUE THREAD

**Issue by rebeccahom** [nyu-software-engineering/drawing-with-friends#55]
Part of user story #10 

The current round is shown on the page to let the players know how many remain.

**Comment by Himanshi22** [comment]
It's not a good practice to leave the tasks/spikes unassigned in your taskboard. Also, assign the required labels to all task/spikes.

**Comment by rebeccahom** [comment]
We have rounds displayed in chat, so this feature is not needed. Closed issue.
